apiVersion: v1
kind: Pod
metadata:
    name: redis-pod
    labels:
        name: redis-pod
        type: demo-voting-app
spec:
    containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379