apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    type: demo-voting-app
spec:
  containers:
    - name: worker-pod
      image: dockersamples/examplevotingapp_worker